### ISSUE TITLE
Globe symbol width 

### ISSUE THREAD

**Issue by GagMirz** [f-person/hayatar#1]
**Phone: iPhone SE 2020**

Globe symbol is very narrow, IDK how on newer and 
with bigger screen models but, it's hard to touch it from first try.
In my experience, I success only after 3-4 times to touch it.

**For comparison apple native layout:**
<img src="https://user-images.githubusercontent.com/34382873/229165245-eabcc4d4-5ecc-4dd4-b80f-a5acbde47524.png " width="180" height="320">

**And hayatar layout:**
<img src="https://user-images.githubusercontent.com/34382873/229165331-d5f0f527-a323-4168-9b7b-08d4a5748468.png" width="180" height="320">

**Comment by f-person** [comment]
Hmm, thanks for reporting this! I'm not yet sure what will be a good solution (because we have more symbols on the bottom row), but I'll try to experiment with it :)

**Comment by f-person** [comment]
*note for future*
Check if I can get the globe width key width of the native keyboard and use that somehow
