### ISSUE TITLE
An empty strip for suggestions is displayed  when "Enable suggestions" is off

### ISSUE THREAD

**Issue by harutyun-s** [f-person/hayatar#14]
![image](https://github.com/f-person/hayatar/assets/66516608/a392bfc2-15ed-4d97-a24c-5732ff4dacd5)

**Comment by f-person** [comment]
Unfortunately, we can't remove that space since iOS disallows third-party keyboards to render anything outside their constraints. So character previews will be cut out, along with callout actions on the upper row.
