### ISSUE TITLE
Second page of symbols.

### ISSUE THREAD

**Issue by GagMirz** [f-person/hayatar#2]
**Phone: iPhone SE 2020**

When entering second page of symbols, there is 
last row of layout is rendered twice.

<img src="https://user-images.githubusercontent.com/34382873/229167090-19ad4eb5-c218-4759-88a3-59aab50e90c3.png" width="180" height="320">

**Comment by f-person** [comment]
This is a known issue, but thanks for reporting; I think it'd be nice to keep all the planned stuff in Issues so that it's easier to navigate it

**Comment by f-person** [comment]
Fixed in the latest release ;)
